[package]
name = "RustyProxy"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] } # ou "rustls-tls" se preferir
futures-util = "0.3" # Necess√°rio para o `next()` em Streams
