[package]
name = "RustyProxy"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23.1" # Usando uma versão estável
httparse = "1.8"
http = "1.0"
bytes = "1.0"
futures-util = { version = "0.3", features = ["sink"] }
