[package]
name = "RustyProxy"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls", "accept", "connect"] } 
httparse = "1.8"
http = "1.0"
bytes = "1.0"
