[package]
name = "RustyProxy"
version = "2.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.27.0"
futures-util = "0.3"
httparse = "1.8"
