[package]
name = "RustyProxy"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
httparse = "1.8"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
