[package]
name = "RustyProxy"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
deadpool = { version = "0.9", features = ["managed"] }
tracing = "0.1"
tracing-subscriber = "0.3"
